---
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    packages:
      - httpd
      - php
      - mariadb-server
      - mariadb
    sitio: ejemplo
    server: www.ejemplo.com.uy
    hostmaster: admin@ejemplo.com.uy

  tasks:
  - name: Instalar software LAMP
    yum:
      name: "{{ packages }}"
      state: latest

  - name: Crear directorio de configuracion de virtualhost
    file:
      path: /etc/httpd/vhost.d
      state: directory
      mode: '0755'
      owner: root

  - name: Agregar directorio de configuracion de virtualhost a httpd.conf
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional vhost.d/*.conf

  - name: Crear directorio de contenido de cirtualhost
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: apache
      group: apache
      mode: '0755'
    loop:
      - /var/www/{{ sitio }}
      - /var/www/{{ sitio }}/html
      - /var/www/{{ sitio }}/cgi-bin

  - name: Crear configuracion de virtualhost
    template:
      src: templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    notify: Reiniciar httpd

  - name: Iniciar y habilitar servicios
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - mariadb-server

  - name: Configurar reglas de firewall
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes
      immediate: yes
    loop:
      - http
      - mysql

  handlers:
    - name: Reiniciar httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
