---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    packages:
      - php
      - mariadb-server
      - mariadb
    sitio: ejemplo
    server: www.ejemplo.com.uy
    hostmaster: admin@ejemplo.com.uy

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat"

  tasks:
  - name: Instalar software LAMP
    yum:
      name: "{{ packages }}"
      state: latest

  - name: Iniciar y habilitar servicios
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - mariadb-server

  - name: Configurar reglas de firewall
    firewalld:
      service: mysql
      state: enabled
      permanent: yes
      immediate: yes

