---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    sitio: ejemplo
    server: www.ejemplo.com.uy
    hostmaster: admin@ejemplo.com.uy

  roles:
  - role: apache-redhat
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-debian
    when: ansible_facts['os_family'] == "Debian"

  - name: Crear directorio de contenido de virtualhost.
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: apache
      group: apache
      mode: '0755'
    loop:
      - /var/www/{{ sitio }}
      - /var/www/{{ sitio }}/html
      - /var/www/{{ sitio }}/cgi-bin

  - name: Crear configuracion de virtualhost.
    template:
      src: templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    notify: Reiniciar httpd
