---
- hosts: webserver
  remote_user: ansible
  become: yes
  become_method: sudo
  vars_files:
  - ./loadbalancer_vars.yml

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-debian
    when: ansible_facts['os_family'] == "Debian"

  tasks:
  - name: Crear configuracion de balanceo de cargas.
    template:
      src: templates/loadbalancer.j2
      dest: /etc/httpd/vhost.d/loadbalancer.conf
      owner: root
      mode: '0644'
    when: ansible_facts['os_family'] == "RedHat"
    notify: Reiniciar httpd

  tasks:
  - name: Crear configuracion de balanceo de cargas.
    template:
      src: templates/loadbalancer.j2
      dest: /etc/apache2/sites-enabled/loadbalancer.conf
      owner: root
      mode: '0644'
    when: ansible_facts['os_family'] == "Debian"
    notify: Reiniciar apache2
    
