---
# tasks file for roles/apache-debian
- name: Instalar Apache Server.
  apt:
    name: apache2
    state: latest

- name: Iniciar y habilitar servicio Apache (apache2).
  service:
    name: apache2
    state: started
    enabled: yes

- name: Configurar reglas de firewall.
  ufw:
    service: "{{ item }}"
    state: enabled
  loop:
    - 80
    - 443
